# Generated by Django 6.0.6 on 2026-06-29 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, default='Available', max_length=20, null=True)),
                ('available_days', models.JSONField(default=list)),
                ('preferred_shift', models.CharField(blank=True, choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night'), ('custom', 'Custom')], max_length=20, null=True)),
                ('preferred_days_off', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'availability',
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conflict_type', models.CharField(choices=[('Leave_Conflict', 'Leave Conflict'), ('Double_Booking', 'Double Booking'), ('Overtime_Violation', 'Overtime Violation'), ('Understaffed_Shift', 'Understaffed Shift'), ('Insufficient_Rest', 'Insufficient Rest')], max_length=50)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('Warning', 'Warning'), ('Info', 'Info')], default='Warning', max_length=20)),
                ('shift_ids', models.JSONField(default=list)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('Ignored', 'Ignored')], default='Open', max_length=20)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'conflicts',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('Sick', 'Sick'), ('Casual', 'Casual'), ('Vacation', 'Vacation'), ('Emergency', 'Emergency'), ('Maternity', 'Maternity')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('submitted_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'leave_requests',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Leave_Approved', 'Leave Approved'), ('Leave_Rejected', 'Leave Rejected'), ('Shift_Changed', 'Shift Changed'), ('Roster_Published', 'Roster Published'), ('Swap_Approved', 'Swap Approved'), ('Swap_Rejected', 'Swap Rejected'), ('Conflict_Detected', 'Conflict Detected')], max_length=30)),
                ('title', models.TextField()),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=50, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'rosters',
            },
        ),
        migrations.CreateModel(
            name='RosterAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Swapped', 'Swapped')], default='Scheduled', max_length=20)),
            ],
            options={
                'db_table': 'roster_shifts',
            },
        ),
        migrations.CreateModel(
            name='RosterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_hours_per_day', models.DecimalField(decimal_places=2, default=12, max_digits=4)),
                ('max_hours_per_week', models.DecimalField(decimal_places=2, default=48, max_digits=5)),
                ('max_hours_per_month', models.DecimalField(decimal_places=2, default=176, max_digits=6)),
                ('max_consecutive_days', models.IntegerField(default=5)),
                ('minimum_rest_hours', models.DecimalField(decimal_places=2, default=11, max_digits=4)),
                ('max_night_per_week', models.IntegerField(default=3)),
                ('max_night_per_month', models.IntegerField(default=10)),
                ('equal_shift_distribution', models.BooleanField(default=True)),
                ('equal_weekend_distribution', models.BooleanField(default=True)),
                ('equal_night_distribution', models.BooleanField(default=True)),
                ('balance_workload', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'roster_rules',
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('shift_type', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night'), ('custom', 'Custom')], default='morning', max_length=20)),
                ('color', models.TextField(default='#3B82F6')),
            ],
            options={
                'db_table': 'shift_templates',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Support Staff', 'Support Staff')], default='Nurse', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('department', models.TextField(blank=True, null=True)),
                ('employment_type', models.CharField(default='Full-time', max_length=20)),
                ('avatar_color', models.TextField(default='#6366f1')),
                ('joined_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff_profiles',
            },
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Manager_Approved', 'Manager Approved'), ('Manager_Rejected', 'Manager Rejected')], default='Pending', max_length=20)),
                ('manager_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shift_swap_requests',
            },
        ),
    ]
