# Generated by Django 6.0.6 on 2026-06-29 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roster', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conflict',
            name='roster',
            field=models.ForeignKey(blank=True, db_column='roster_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='roster.roster'),
        ),
        migrations.AddField(
            model_name='rosterassignment',
            name='roster',
            field=models.ForeignKey(db_column='roster_id', on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='roster.roster'),
        ),
        migrations.AddField(
            model_name='rosterassignment',
            name='shift',
            field=models.ForeignKey(blank=True, db_column='shift_template_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='roster.shifttemplate'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rosterassignment',
            name='staff',
            field=models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_shifts', to='roster.staffprofile'),
        ),
        migrations.AddField(
            model_name='roster',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rosters', to='roster.staffprofile'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='staff',
            field=models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='roster.staffprofile'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='roster.staffprofile'),
        ),
        migrations.AddField(
            model_name='availability',
            name='staff',
            field=models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='roster.staffprofile'),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='current_shift',
            field=models.ForeignKey(db_column='requester_shift_id', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_as_primary', to='roster.rosterassignment'),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='requested_shift',
            field=models.ForeignKey(blank=True, db_column='offered_shift_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_as_offer', to='roster.rosterassignment'),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='requested_staff',
            field=models.ForeignKey(blank=True, db_column='requested_staff_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_swaps', to='roster.staffprofile'),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='requester',
            field=models.ForeignKey(db_column='requester_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_swaps', to='roster.staffprofile'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='idx_notif_user'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='idx_notif_is_read'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='idx_notif_created'),
        ),
        migrations.AddIndex(
            model_name='rosterassignment',
            index=models.Index(fields=['roster'], name='idx_r_shifts_roster'),
        ),
        migrations.AddIndex(
            model_name='rosterassignment',
            index=models.Index(fields=['staff'], name='idx_r_shifts_staff'),
        ),
        migrations.AddIndex(
            model_name='rosterassignment',
            index=models.Index(fields=['shift_date'], name='idx_r_shifts_date'),
        ),
        migrations.AlterUniqueTogether(
            name='rosterassignment',
            unique_together={('staff', 'shift_date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='roster',
            index=models.Index(fields=['status'], name='idx_rosters_status'),
        ),
        migrations.AddIndex(
            model_name='roster',
            index=models.Index(fields=['start_date', 'end_date'], name='idx_rosters_dates'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['staff'], name='idx_leave_staff_id'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status'], name='idx_leave_status'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date', 'end_date'], name='idx_leave_dates'),
        ),
        migrations.AddIndex(
            model_name='conflict',
            index=models.Index(fields=['roster'], name='idx_conflicts_roster'),
        ),
        migrations.AddIndex(
            model_name='conflict',
            index=models.Index(fields=['status'], name='idx_conflicts_status'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['staff'], name='idx_avail_staff_id'),
        ),
        migrations.AddIndex(
            model_name='swaprequest',
            index=models.Index(fields=['requester'], name='idx_swaps_requester'),
        ),
        migrations.AddIndex(
            model_name='swaprequest',
            index=models.Index(fields=['status'], name='idx_swaps_status'),
        ),
    ]
