# Generated by Django 6.0.6 on 2026-06-29 09:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflict',
            name='conflict_type',
            field=models.CharField(choices=[('Leave_Conflict', 'Leave Conflict'), ('Double_Booking', 'Double Booking'), ('Overtime_Violation', 'Overtime Violation'), ('Understaffed_Shift', 'Understaffed Shift'), ('Insufficient_Rest', 'Insufficient Rest'), ('Availability_Violation', 'Availability Violation'), ('Overstaffed_Shift', 'Overstaffed Shift'), ('Qualification_Mismatch', 'Qualification Mismatch'), ('Department_Constraint_Violation', 'Department Constraint Violation')], max_length=50),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
