# Generated by Django 6.0.6 on 2026-06-29 11:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_alter_conflict_conflict_type_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='conflict',
            old_name='staff',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='message',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='shift_ids',
        ),
        migrations.AddField(
            model_name='conflict',
            name='actual_value',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conflict',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conflict',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='conflict',
            name='expected_value',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conflict',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conflict',
            name='ignored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conflict',
            name='ignored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ignored_conflicts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conflict',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='conflict',
            name='optional_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conflict',
            name='planning_board_redirect',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='conflict',
            name='reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='conflict',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conflict',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conflict',
            name='shift',
            field=models.ForeignKey(blank=True, db_column='shift_template_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='roster.shifttemplate'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='suggested_resolution',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='conflict',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='conflict',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='conflict_type',
            field=models.CharField(choices=[('DOUBLE_BOOKING', 'Double Booking'), ('SHIFT_OVERLAP', 'Shift Overlap'), ('LEAVE_VIOLATION', 'Leave Violation'), ('AVAILABILITY_VIOLATION', 'Availability Violation'), ('REST_RULE_VIOLATION', 'Rest Rule Violation'), ('OVERTIME_LIMIT_EXCEEDED', 'Overtime Limit Exceeded'), ('UNDERSTAFFED_SHIFT', 'Understaffed Shift'), ('OVERSTAFFED_SHIFT', 'Overstaffed Shift'), ('MAX_CONSECUTIVE_DAYS_EXCEEDED', 'Max Consecutive Days Exceeded'), ('MAX_NIGHT_SHIFT_LIMIT_EXCEEDED', 'Max Night Shift Limit Exceeded')], max_length=50),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium')], default='Medium', max_length=20),
        ),
    ]
