# Generated by Django 6.0.6 on 2026-06-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_rename_staff_conflict_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
