# Generated by Django 6.0.6 on 2026-06-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_roster_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
